### ISSUE TITLE
Crashes on application launch (Android 11)

### ISSUE THREAD

**Issue by maxim-narchuk-cleverside** [adaptyteam/AdaptySDK-Unity#14]
Crashes on application launch

**Platform**: Android

**Devices**: Samsung Galaxy S20 FE 5G, Motorola One Hyper

**OS Version**: Android 11

**Versions of Adapty SDK**:

`<?xml version="1.0" encoding="UTF-8"?>
<dependencies>
	<androidPackages>
		<androidPackage spec="io.adapty:android-sdk:2.9.1">
			<repositories>
				<repository>https://repo.maven.apache.org/maven2/</repository>
			</repositories>
		</androidPackage>
	</androidPackages>
	<iosPods>
		<iosPod name="Adapty" version="2.9.2" minTargetSdk="9.0">
		</iosPod>
	</iosPods>
</dependencies>
`

Crash-log

UserAgentRetriever$retrieveUserAgent$1.invoke
android.webkit.WebViewFactory$MissingWebViewPackageException - Failed to load WebView provider: No WebView installed

```
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1355)
       at com.adapty.internal.utils.UserAgentRetriever$retrieveUserAgent$1.invoke(UserAgentRetriever.kt:35)
       at com.adapty.internal.utils.UserAgentRetriever$retrieveUserAgent$1.invoke(UserAgentRetriever.kt:32)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by vladd-g** [comment]
Hi @maxim-narchuk-cleverside, thank you for the report! Could you please try replacing `2.9.1` with `2.9.2` in the line `<androidPackage spec="io.adapty:android-sdk:2.9.1">`?

**Comment by x401om** [comment]
I will close the issue due to inactivity. Please feel free to reopen it if you believe you need help or just message us on support@adapty.io
